### ISSUE TITLE
text overflow

### ISSUE THREAD

**Issue by nomoreheroesparadise** [bluejamesbond/Waterfall.js#1]
Is it possible to set text-overflow hidden in Waterfall.Theme.Separator ? And if so it would be much appricated to give some kind of tips.

**Comment by bluejamesbond** [comment]
It has been a while since I looked at the project. But I don't believe you can use text-overflow there since it is an overlay. But, you can cut your string to make sure it stays within the boundary by using the `trim` attribute like this - https://github.com/bluejamesbond/Waterfall.js/blob/gh-pages/example/index.jsx#L160. If that doesn't work let me know, I can dig deeper.

**Comment by bluejamesbond** [comment]
Your welcome! Ill close this for now. Feel free to reopen as needed.
